### ISSUE TITLE
Como utilizar a biblioteca ?

### ISSUE THREAD

**Issue by mozgbrasil** [DenysXavier/WSBoletoSantander#1]
Ola 

Boa Tarde

Tenho interesse no uso da biblioteca, como posso utilizar a biblioteca para ser gerado um Boleto do Santander ?

**Comment by DenysXavier** [comment]
Boa noite, @mozgbrasil !

A partir de semana que vem começarei a revisar e documentar o projeto na Wiki interna.

Enquanto isso, pode usar um guia simplificado que fiz.

[doc_ws_boleto_santander.pdf](https://github.com/DenysXavier/WSBoletoSantander/files/877426/doc_ws_boleto_santander.pdf)

**Comment by sarettaweb** [comment]
Boa tarde Estou tentando usar seu código mais está dando esse erro

Fatal error: Class 'TIExpert\WSBoletoSantander\Convenio' not found in E:\htdocs\boletoSantader\testando.php on line 12

vc pode me ajudar? Muito bom o código

André Saretta

**Comment by sarettaweb** [comment]
Usei o composer para instalar... Tem como passar um modelo de como se usa ou até mesmo um arquivo de exemplo

**Comment by DenysXavier** [comment]
Para facilitar o uso da biblioteca, o documento dessa issue foi usado como base para redigir o Guia Básico de Uso do README.

Ver issue #33.
