### ISSUE TITLE
You don't have permission to access /dl-ticket-services/TicketEndpointService on this server.

### ISSUE THREAD

**Issue by andressamiki** [DenysXavier/WSBoletoSantander#17]
Olá!
Estou tentando usar seu código mais está dando esse erro.

Forbidden

You don't have permission to access /dl-ticket-services/TicketEndpointService on this server.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

Alguém pode me ajudar?

Aguardo a sua resposta e agradeço desde já.

**Comment by DenysXavier** [comment]
Olá, @andressamiki!

Provavelmente, você ainda não tem seu certificado cadastrado no Santander.

Antes de usar o serviço deles é necessário passar seu certificado digital.

Dê uma olhada na issue #1 que tem um documento chamado doc_ws_boleto_santander.pdf que explica um pouco sobre o certificado.

Até mais!

**Comment by d3rf** [comment]
Eu estava com esse problema.  Tem um procedimento explicado aqui como preparar o certificado, após isso, envie para eles e é só aguardar.

**Comment by andressamiki** [comment]
Ainda estou com o problema. Entrei em contato com o banco e eles pediram para gerar 5 boleto e suas remessas.

**Comment by d3rf** [comment]
Consegui fzer o meu funcionar com SOAP mesmo, tudo bonito, vou tentar enviar um branch pro owner do projeto dar uma olhada.

**Comment by andressamiki** [comment]
@d3rf  Você pode me mandar? Estou tentando desde setembro.

**Comment by d3rf** [comment]
Claro, só 1m pfv

**Comment by d3rf** [comment]
[BoletoController.class.php.zip](https://github.com/DenysXavier/WSBoletoSantander/files/1598389/BoletoController.class.php.zip)

Depois eu implemento aqui. Me falta tempo qq dúvida me chama

**Comment by andressamiki** [comment]
@d3rf  Para gerar o certificado com o banco, você precisou mandar algo para ele?

**Comment by d3rf** [comment]
O certificado vc não gera com o banco, a empresa compra um na cidade, to tipo A1 ou A3 CNPJ em arquivo. Tipo esses aqui https://sigcertificadora.com.br/ecnpj

**Comment by d3rf** [comment]
@andressamiki Depois, vc receberá um arquiv PFX aí é só seguir as instruções e enviar para eles um arquivo do tipo .crt com sua chave publica. Tem o procedimento aqui em algum lugar. Quer pegar meu Skype ou Facebook para que possa te ajudar nessa parte inicial?

**Comment by andressamiki** [comment]
@d3rf Eu quero sim. Obrigada pelo auxílio.

**Comment by d3rf** [comment]
Skype frederico.fiuza Facebook fb.me/frederico.fiuza

**Comment by DenysXavier** [comment]
Fechado por estar muito tempo sem comentários.

Aparentemente, problema também foi resolvido.

Se necessário, a issue pode ser reaberta.

**Comment by eueliton** [comment]
pessoal....estou com o mesmo erro "You don't have permission to access /dl-ticket-services/TicketEndpointService on this server." . O certificado já está OK lá no santander, pois através do navegador com o certificado e com o cartão do serasa acessa a url sem problemas.

**Comment by DenysXavier** [comment]
Boa tarde, @eueliton!

Espero que a essa altura você já tenha solucionado seu problema.

Caso contrário, verifique a discussão que está acontecendo na issue #34. Talvez você consiga encontrar uma solução naquela issue ao invés dessa.

**Comment by eueliton** [comment]
Solucionei pessoal. O problema era o tipo de certificado que estava utilizando. O certificado precisa ter uma chave pública e uma privada. Senão não estabelece a conexão.
