### ISSUE TITLE
Versão "2" do Santander?

### ISSUE THREAD

**Issue by italopaulino** [DenysXavier/WSBoletoSantander#18]
Bom dia!
Recebi a última documentação do SANTANDER e ele aponta o URL de cobrança para: https://ymbcash.santander.com.br/ymbsrv/CobrancaV2EndpointService

Veja que apareceu um "V2" aí no meio. Esse script já suporta isso? Você chegou a verificar?

Obrigado e um abraço.

**Comment by DenysXavier** [comment]
Boa tarde, @italopaulino!

O Santander não me enviou nada por enquanto.

Vou verificar com eles e, assim que possível, faço uma nova release com o novo endpoint.


Obrigado!

**Comment by italopaulino** [comment]
Se quiser, me passa seu e-mail que eu envio a documentação que eu recebi.
Tenho interesse em contribuir com você, pois vou realmente usar a ferramenta.
Um abraço.

**Comment by DenysXavier** [comment]
Por favor, pode me enviar em denysxavier.github@outlook.com.

Obrigado, @italopaulino!

**Comment by DenysXavier** [comment]
Resolvido no PR #20
