### ISSUE TITLE
Erro ao utilizar

### ISSUE THREAD

**Issue by coixa** [DenysXavier/WSBoletoSantander#2]
Olá, estou tentando implementar seu código mas estou travado nessa mensagem de erro retornado pelo Santander:

Erro: O serviço de inclusão de título do Santander retornou um erro. Código: -1

Ver: http://www.websiteemsantos.com.br/c2017/xindex.php
+ http://www.websiteemsantos.com.br/c2017/xindex.php?dump=1

Espero que consiga me ajudar :)

Alias, parabéns pelo código!

**Comment by DenysXavier** [comment]
Boa noite, @coixa !

Desculpe-me a demora, mas, vamos lá.

Pelo que estou vendo, o erro está acontecendo por conta de problema de certificado.

Isso pode estar acontecendo do seu lado ou do lado do banco.

Primeiro, certifique-se do seu lado. O certificado digital do servidor que irá se comunicar com o Santander está configurado corretamente no arquivo config.ini do WSBoletoSantander?

Veja isso nas seguintes diretivas:

```INI
[certificado]
arquivo = "/var/www/html/seu_certificado_digital.pem"
senha = "Senha do seu certificado"
tipo_arquivo = "PEM"
```

Se estiver correto, então, talvez você ainda não tenha registrado seu certificado junto ao Santander. Entre em contato com eles e passe seu certificado digital.

Apenas lembrando que seu certificado digital deve permitir que o endpoint possa comprovar sua identidade.

Qualquer coisa, dê uma olhada no arquivo que subir como resposta da issue #1.

**Comment by coixa** [comment]
Olá, realmente tinha problemas no certificado e para completar o Santander passou o código da estação errado e estava apanhando.

Porém agora ao consultar um título, recebo um erro que não está no manual enviado pelo Santander.

https://www.websiteemsantos.com.br/c2017/xindex.php

Segue link caso você consiga me dar uma luz!

Obrigado pela resposta!

**Comment by DenysXavier** [comment]
Olá, @coixa!

Aparentemente, esse erro é realmente do lado do servidor do Santander. E, se minhas pesquisas estão certas, é resultado duplicado ou múltiplo onde a query está esperando um resultado único.

Primeiramente, confirme que você não tentou burlar a regra máxima do WS do Santander:

Todo boleto é único por NSU + data + convênio.

Ou seja, você não registrou dois boletos diferentes com o mesmo NSU na mesma data, certo?

Quando você foi sondar, você também pediu um tíquete específico de sondagem. Correto?

Você pode fazer isso passando apenas uma instância de Convenio para o método `solicitarTicketSondagem`. No tíquete retornado, você informa o NSU e a data que você registrou o boleto.

Se você fez tudo isso acima direitinho, então, você vai ter que ver no banco mesmo, pois há uma grande possibilidade de que deu algum problema na query do banco de dados deles.

Abraço!

**Comment by coixa** [comment]
Olá Denys, realmente era isso, obrigado pela resposta rápida!!!

Se possível gostaria de fazer uma última pergunta hehe Na Sondagem de Titulo ele não deveria retornar a situação do boleto? Se ele foi pago ou não?

**Comment by DenysXavier** [comment]
Boa tarde, @coixa!

Esse projeto foi feito para atender as necessidades de onde trabalho.

No caso da sondagem, não havia - e ainda não há - necessidade de verificar se o boleto está pago ou não.

O que não quer dizer que verificar se ele está pago não seja importante.

Esse projeto é open-source. Se você achar interessante que ele deva ter essa característica, então, abra uma issue pedindo isso. A funcionalidade entrará no planejamento e poderá ser implementada.

Assim, o projeto vai crescendo e melhorando.

Portanto, se essa discussão chegou ao fim, por favor, feche esta issue e abra uma nova pedindo a funcionalidade. :wink:

Até!
