### ISSUE TITLE
Erro na Instalação

### ISSUE THREAD

**Issue by italopaulino** [DenysXavier/WSBoletoSantander#25]
Tentei realizar a instalação em um Windows, porém retornou 1 erro:

D:\Sites\sites\WSBoletoSantander-master>composer require tiexpert/ws-boleto-santander
Using version ^1.1 for tiexpert/ws-boleto-santander
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package tiexpert/ws-boleto-santander No version set (parsed as 1.0.0) is satisfiable by tiexpert/ws-
boleto-santander[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by d3rf** [comment]
Cara, verifica seu composer

Em qui, 28 de jun de 2018 19:55, Italo Paulino <notifications@github.com>
escreveu:

**Comment by italopaulino** [comment]
Consegui fazendo assim: composer require tiexpert/ws-boleto-santander:1.0.0

Você disponibiliza algum tipo de documentação de como usá-lo? Queria já testá-lo.

Obrigado.

**Comment by DenysXavier** [comment]
Olá, @italopaulino!

O que @d3rf disse pode dar certo.

Execute `composer --version` e veja qual versão você tem instalado. A versão mais atual hoje é 1.6.5.

Se tiver uma versão mais antiga, tente atualizar com `composer self-update`.

Rode novamente o comando `require`.

Se ainda não der certo, por favor, poste seu composer.json aqui para vermos.

**Comment by DenysXavier** [comment]
Boa tarde, @italopaulino!

Revendo sua issue, talvez eu tenha descoberto o que pode estar dando errado.

Aparentemente, você copiou meu repositório master (ou baixou o .zip do projeto inteiro, não tem diferença). E, então, tentou incluir o meu projeto dentro dele mesmo com o `require`. Confuso, né?

Acho que seu problema está no uso do Composer.

Se você está iniciando agora um projeto, recomendo fazer o seguinte:

1. Crie uma pasta vazia, entre nela pelo prompt e rode `composer init`. Isso irá iniciar o seu projeto usando uma espécie de passo-a-passo.

2. Primeiro, ele irá pedir o nome do seu projeto (ex.: italopaulino/meu-projeto).

3. Depois pedirá uma descrição do projeto. E, depois o autor (você), por exemplo, Italo Paulino &lt;seu_email@server.com&gt;

4. Para ficar mais simples, as próximas três perguntas, você irá ignorar apertando ENTER em Minimum Stability, Package Type e License.

5. Nas duas próximas perguntas relativas ao require, você irá responder `no`.

6. Por fim, confirme a geração no final com `yes`.

Veja que sua pasta tem um novo arquivo chamado _composer.json_. Essa é a informação sobre o seu projeto.

Como seu projeto depende do meu, use o comando require assim: `composer require tiexpert/ws-boleto-santander`.

Como até aqui, você ainda não tinha feito a instalação, o Composer irá obter as dependências e já fazer a instalação.

Dando tudo certo, ele irá criar um arquivo `composer.lock`.

Pronto! Você já pode codificar seu projeto.

**Recomendo a leitura da documentação do Composer**, começando pelo uso básico (https://getcomposer.org/doc/01-basic-usage.md). Você não precisará da introdução, pois você já passou da etapa de instalação.

Também, recomendo muito você ler sobre o **Autoloading do Composer** (https://getcomposer.org/doc/01-basic-usage.md#autoloading) que irá te facilitar bastante.

Espero que isso ajude.

**Comment by italopaulino** [comment]
Denys, deu certo!
Muito obrigado.
