### ISSUE TITLE
Montar boleto para impressão

### ISSUE THREAD

**Issue by MReis89** [DenysXavier/WSBoletoSantander#26]
@DenysXavier, ao registrar um titulo o banco retorna um XML com os dados do titulo e código de barras.
Como poderia acessar esse XML para montar o layout do boleto ou há alguma método parar gerar o boleto?

**Comment by DenysXavier** [comment]
Olá, @MReis89!

Esse projeto eu uso onde trabalho e não temos a necessidade de gerar código de barras a partir dele, pois usamos um outro software para fazer isso. Entretanto, há na documentação do Santander duas propriedades que, de fato, não implementei: código de barras e linha digitável.

O software que usamos para gerar boletos é um bem antigo chamado PHP Boleto que fizemos algumas adaptações. Acredito que ele nem deva mais existir, apenas seus derivados. Dê uma olhada, por exemplo, no https://boletophp.com.br.

Se você preferir fazer seu próprio projeto para geração de boleto para impressão e quiser usar o meu como dependência e julgar necessário essas duas propriedades, por favor, abra uma nova issue pedindo a inclusão dos dois campos que eu o planejo para uma nova release.

**Comment by MReis89** [comment]
Olá @DenysXavier .

Verdade! Vou dar uma olhada no PHP Boleto para gerar o meu layout, já utilizei ele em outro projeto mas não me recordava. Obrigado!

Fiz um Fork do seu projeto e posso tentar implementar as opções do código de barras/linha digitável e mandar um PR.

**Comment by DenysXavier** [comment]
Claro.

À vontade.
