### ISSUE TITLE
Documentação do Banco

### ISSUE THREAD

**Issue by astherweb** [DenysXavier/WSBoletoSantander#27]
Olá... tem como disponibilizar os manuais do Banco Santander pra usar o Web Service para comunicação de cobrança?

**Comment by DenysXavier** [comment]
Boa tarde, @astherweb!

Se quiser saber como usar esta biblioteca, veja o documento doc_ws_boleto_santander.pdf que está na minha resposta da issue #1.

Agora, se você estiver se referindo à documentação do banco, acredito que você pode pedir diretamente para o Santander. Ou me envie seu e-mail que eu te repasso o último que eu tenho.

Meu e-mail é denysxavier.github@outlook.com.

**Comment by astherweb** [comment]
Mandei o email. Obrigado.

**Comment by DenysXavier** [comment]
Olá, @astherweb!

Já te encaminhei.

Vou fechar essa issue.

Se julgar necessário, por reabri-la.
