### ISSUE TITLE
PFX Vs PEM

### ISSUE THREAD

**Issue by rafinha90** [DenysXavier/WSBoletoSantander#34]
Olá.

Estou com um problema com os certificados.

Tenho um certificado PFX que funciona normalmente para o envio de remessas, porém ao convertê-lo para PEM, tento utilizá-lo com a biblioteca de vocês e fico recebendo:

`<TicketResponse>`
`             <message>Error: java.lang.Exception: Access denied: certificate not found</message>`
`              <retCode>-1</retCode>`
`</TicketResponse>`

Converti o certificado utilizando o seguinte comando:

`openssl pkcs12 -in certicado1.pfx -out certicado2.pem -nodes`

Poderia me dar uma luz no que estou fazendo errado?

Também já tentei utilizando `-clcerts` ao invés de `-nodes` e continuo recebendo o mesmo erro

**Comment by alanricardox** [comment]
Olá :)

Estou com o mesmo problema, retorna exatamente este mesmo erro.

Tentei gerar o PEM novamente, testei o PFX que já utilizo para outras operações mas o erro continua.

O Santander enviou os DOCs o que indica que o certificado foi aprovado.

Alguma ideia do que pode ser?

**Comment by mssartori** [comment]
Também estou com o mesmo problema. Já tentei várias versões diferentes do OpenSSL, tanto 32 quanto 64, e vários parâmetros de saída diferentes na hora da conversão, e nada.

**Comment by DenysXavier** [comment]
Boa noite, pessoal!

Ainda não tinha me deparado com esse tipo de erro.

Primeiramente, use preferencialmente o PEM, não use o PFX.

Segundo, não sei dizer exatamente de que certificado esse erro está se referindo. Vamos supor que seja o certificado do cliente (que está no servidor de vocês).

Talvez, vocês não estão indicando o caminho correto dos seus PEM para que o comunicador possa passar o certificado para o banco Santander.

Tentem alterar seus arquivos _config.ini_ para o caminho correto do PEM.

Aconselho inclusive a usar o caminho completo do sistema para evitar falha. Ex.: /var/www/ ... (Linux) ou C:/inetpub/... (Windows).

```ini
[certificado]
arquivo = "/var/www/html/meu_certificado_digital.pem"
senha = "Senha do seu certificado"
tipo_arquivo = "PEM"
arquivo_ca = "/var/www/html/entrust_g2_ca.cer"
```

Dê uma olhada também nas [Questões Importantes](https://github.com/DenysXavier/WSBoletoSantander#quest%C3%B5es-importantes) do README.

Espero que funcione.

**Comment by alanricardox** [comment]
Aqui funcionou. 

O Santander me ligou e o problema era que o certificado ainda não tinha sido 100% homologado.

Eu mandei minha chave pública para eles verificarem novamente (durante uma ligação) e após isso tudo funcionou, muito obrigado @DenysXavier

**Comment by rafinha90** [comment]
@DenysXavier o caminho para o certificado está correto.

Acredito que o problema esteja realmente com o banco, ou que o cliente nos enviou o certificado errado, apesar de afirmar que enviou o correto e que utiliza o mesmo certificado para enviar as remessas internas deles.

Já devolvi a bola para o cliente, o mesmo está entrando em contato com o Banco. Atualizarei aqui assim que tiver mais detalhes.

Mas desde já, muito obrigado pela atenção.

**Comment by DenysXavier** [comment]
OK, @alanricardox e @rafinha90!

O mais provável é que esse erro seja realmente algum cadastro com o banco de ainda não está completo ou finalizado.

@mssartori, tente verificar se está tudo certo com o banco e boa sorte.

Vou deixar a issue aberta mais um tempo.

**Comment by dlhenke** [comment]
Olá onde conseguir estes certificados ?

**Comment by d3rf** [comment]
No certificado deve constar as 3 Chaves públicas da receita Federal da
autoridade certificadora e da empresa

Em qua, 14 de nov de 2018 12:23, Durval Luis Henke <notifications@github.com
escreveu:

**Comment by dlhenke** [comment]
Olá quanto aos certificados é possível obter gratuitamente pela COMODO 1 ano, Obrigatório utilizar o Firefox para obtenção do certificado.. 
Uma questão.. o certificado devo utiliza-lo com ou sem a chave publica quando exportar com openssl para PEM ?
openssl pkcs12 -in Certificates.p12 -nokeys -out publiccert.pem -nodes
e
openssl pkcs12 -in Certificates.p12 -nocerts -out privatekey.pem -nodes

**Comment by DenysXavier** [comment]
Olá, @dlhenke!

Para não poluir muito essa issue, criei outras com suas dúvidas.

Por favor, qualquer assunto relativo a "como conseguir estes certificados", vá para issue #37.

Se for relativo a "utilizar certificado com ou sem chave pública", vá para a issue #38.

Obrigado!

**Comment by mssartori** [comment]
> OK, @alanricardox e @rafinha90!
> 
> O mais provável é que esse erro seja realmente algum cadastro com o banco de ainda não está completo ou finalizado.
> 
> @mssartori, tente verificar se está tudo certo com o banco e boa sorte.
> 
> Vou deixar a issue aberta mais um tempo.

Era problema no certificado. Obrigado!
