### ISSUE TITLE
PHP Notice:  curl_setopt_array(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in

### ISSUE THREAD

**Issue by brenogalinari** [DenysXavier/WSBoletoSantander#35]
Quando tento gerar um boleto com o seguinte código, recebo essa mensagem de erro: 

PHP Notice:  curl_setopt_array(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead in /.../vendor/tiexpert/ws-boleto-santander/src/ComunicadorCurlSOAP.php on line 37

$convenio = new Convenio();
        $convenio->setCodigoBanco("0033");
        $convenio->setCodigoConvenio('meucodigo');
        $pagador = new Pagador('01', '53662187302', 'Breno Galinari Barçante', 'Rua alguma coisa', 'Algum Bairro', 'Governador Valadares', 'MG', '35057400');
        $instrucoes = new InstrucoesDeTitulo();
        $titulo = new Titulo(999.99, '101', '1020', '16112018', 'Sem nenhuma mensagem', '13112018', 32, $instrucoes);
        $boleto = new Boleto($convenio, $pagador, $titulo);
        $comunicador = new ComunicadorCurlSOAP();
        $svc = new BoletoSantanderServico($comunicador);
        $ticket = $svc->solicitarTicketInclusao($boleto);

Alguém mais passou por isso e sabe como resolver ?

**Comment by DenysXavier** [comment]
Boa tarde, @brenogalinari!

Após verificar mais atentamente a sua issue, tratei-a com maior prioridade. Pois descobri que, apesar de remota a chance, havia a possibilidade de risco de segurança.

Há uma configuração booleana no config.ini chamada `assegurar_endpoint` que serve para indicar na configuração da extensão cURL se é necessário verificar as credenciais do servidor durante a comunicação, sendo 1 (true), o servidor deve ser verificado e 0 (false), o servidor não deve ser verificado. 

Esse mesmo valor era usado em duas variáveis de configuração, CURLOPT_SSL_VERIFYPEER e CURLOPT_SSL_VERIFYHOST.

O maior propósito dessa configuração é facilitar o debug, e jamais deve ser `false` em um ambiente de produção.

Entretanto, acontece que, se for definido 1 para CURLOPT_SSL_VERIFYHOST também, a extensão cURL irá exigir o certificado do servidor, contudo não irá verificar a procedência. Ou seja, a extensão só exige que o servidor retorne um certificado, mesmo que não seja o certificado correto.

Desde a versão 7.28 da extensão cURL, não é mais possível definir CURLOPT_SSL_VERIFYHOST como 1. E isso foi exatamente o que aconteceu com seu servidor.

Como ele está com a extensão atualizada, quando o WSBoletoSantander tentou definir CURLOPT_SSL_VERIFYHOST como 1, seu servidor automaticamente ignorou essa ordem e definiu como 2 (nível mais seguro). Contudo, talvez nem todo mundo tenha a sorte de ter seu servidor com as últimas atualizações. Portanto, lancei um hotfix para essa vulnerabilidade.

Baixe a nova versão [1.2.1](https://github.com/DenysXavier/WSBoletoSantander/releases/tag/1.2.1).

Ou, se utilizou o Composer, execute `composer update` para atualizar para a última versão.

Muito obrigado!

**Comment by brenogalinari** [comment]
@DenysXavier Muito obrigado pela atenção e pela resposta.
