### ISSUE TITLE
o certificado devo utiliza-lo com ou sem a chave publica

### ISSUE THREAD

**Issue by DenysXavier** [DenysXavier/WSBoletoSantander#38]
Uma questão.. o certificado devo utiliza-lo com ou sem a chave publica quando exportar com openssl para PEM ?
openssl pkcs12 -in Certificates.p12 -nokeys -out publiccert.pem -nodes
e
openssl pkcs12 -in Certificates.p12 -nocerts -out privatekey.pem -nodes

_Originally posted by @dlhenke in https://github.com/DenysXavier/WSBoletoSantander/issues/34#issuecomment-438867156_

**Comment by DenysXavier** [comment]
Boa noite, @dlhenke!

Não sou profundo entendedor de certificados digitais, mas se esse será o PEM que você irá usar na configuração do WSBoletoSantander, acredito que você tenha que exportar **COM** a chave pública. Pois o servidor do Santander terá que usar sua chave pública para criptografar a conexão entre o seu servidor e o dele.

**Comment by DenysXavier** [comment]
Bom dia, @dlhenke!

Confirmado. É necessário ter a chave pública no PEM também.

@eueliton teve o mesmo problema e respondeu na issue #17:

> Solucionei pessoal. O problema era o tipo de certificado que estava utilizando. O certificado precisa ter uma chave pública e uma privada. Senão não estabelece a conexão.

**Comment by eueliton** [comment]
Eu peguei o certificado pela SERASA. Lá eles tem o A1 e o A3. Precisa ser o A1. eles geram direto o arquivo PFX, com as duas chaves nele. Daí só usar um comando SSL para converter para a extensão que quer.
