### ISSUE TITLE
Testes de conectividade do Santander no Linux

### ISSUE THREAD

**Issue by valderind4** [DenysXavier/WSBoletoSantander#45]
Pessoal,

Gostaria de saber como realizar os testes solicitados pelo Santander(acesso ao WSDL e execução do .jar) no ambiente Linux utilizando o .pfx ou mesmo o .PEM convertido do sistema, ou isso realmente só pode ser feito via Windows? Digo isto pq o pessoal da certificadora falou que não é possível instalar o certificado no Linux assim como acontece no windows. 

Vocês que utilizam servidor linux como passaram dessa fase para poder chegar na fase de geração de um boleto teste?

PS: O Servidor é um Centos 6

**Comment by DenysXavier** [comment]
Olá, @valderind4!

Pelo que estou vendo, você está em ambiente Java e não PHP. Se isto for verdadeiro, então, o WSBoletoSantander não servirá para você.

Em relação ao certificado, é possível utilizá-lo no Linux, mas você provavelmente terá que convertê-lo para PEM e, talvez, guardá-lo tanto na pasta de certificados do Linux quanto do Java.

> Para converter seu PFX em PEM, use o [OpenSSL](https://www.openssl.org/) e o comando abaixo.
>
> ```console
> openssl pkcs12 -in seu_certificado.pfx -out seu_certificado_em_outro_formato.pem -nodes
> ```

Dependendo do seu servidor de aplicação, você também terá que guardar seu certificado lá.

Isso é só um palpite. Pois, nunca trabalhei com o registro de boleto do Santander no Java.

**Comment by valderind4** [comment]
> Olá, @valderind4!
> 
> Pelo que estou vendo, você está em ambiente Java e não PHP. Se isto for verdadeiro, então, o WSBoletoSantander não servirá para você.
> 
> Em relação ao certificado, é possível utilizá-lo no Linux, mas você provavelmente terá que convertê-lo para PEM e, talvez, guardá-lo tanto na pasta de certificados do Linux quanto do Java.
> 
> > Para converter seu PFX em PEM, use o [OpenSSL](https://www.openssl.org/) e o comando abaixo.
> > ```
> > openssl pkcs12 -in seu_certificado.pfx -out seu_certificado_em_outro_formato.pem -nodes
> > ```
> 
> Dependendo do seu servidor de aplicação, você também terá que guardar seu certificado lá.
> 
> Isso é só um palpite. Pois, nunca trabalhei com o registro de boleto do Santander no Java.

Olá Denys, 

Muito obrigado pela reposta, na verdade a intenção é de usar essa API PHP, porém como testes de conectividade o Santander passa alguns testes que inclui rodar um .jar que eles nos fornecem o qual executa o teste de conectividade envolvendo o certificado, a máquina e o servidor do Santander.

Vocês não precisaram fazer esse tipo de teste?


> Após importar o certificado em sua máquina local ou servidor e conseguir realizar a obtenção do ticket, execute o seguinte roteiro de teste em Java.
> 
> TESTE DLB:
> 
> O teste em Java que pode ser obtido através do link: https://drive.google.com/open?id=1ji8WEQNhhSDAdw3fQPBOeSdA0SsX9rZW
> 
>                                                                               
> O Arquivo está criptografado e compactado com o zip.
> Renomeie o .txt para zip. A senha para descompactar é Santander.
> 
> Para utilizar o teste Java seguir o seguinte procedimento:
> 
>      *   Adicionar o parâmetro ambiente onde T corresponde à ambiente de Teste;
>      *   Adicionar o parâmetro ambiente onde P corresponde à ambiente de Produção;
> 
> 
>  Exemplo para testes:
> 
>  
> 
> Obs: Você precisa estar dentro da pasta onde está o certificado para realizar este teste.
> 
>  
> 
> Linha modelo :
> 
>  
> 
> ·         java -jar TesteDLBTicket.jar P PKCS12 keystore.p12  password > Nome_do_Log.txt
> 
>  
> 
> Linha de exemplo editada para execução:
> 
>  
> 
> ·         java –jar TesteDLBTicket.jar P PKCS12 certificado_teste.pfx  (informar a senha do certificado sem o parênteses) >20190321.txt
> 
> 
> Obs: Assim que finalizar o teste peço que encaminhe o log(txt) de retorno.
> 
> 
> Obs: Rode o teste DLB e envie o resultado para que eu possa analisar e ajudar a corrigir caso ocorra algum erro.

**Comment by DenysXavier** [comment]
Olá, @valderind4!

Você já tentou fazer isso que estão pedindo?

Acabei de fazer no Linux e foi sem problemas.

Como eu não estou no meu serviço, fiz uma máquina virtual e um certificado auto-assinado. O resultado foi:

```console
denys@denys-VirtualBox:~$ java -jar TesteDLBTicket.jar T PKCS12 certificate.pfx abc123 > Log.txt
com.sun.xml.internal.ws.wsdl.parser.InaccessibleWSDLException: 2 counts of InaccessibleWSDLException.

java.io.IOException: Server returned HTTP response code: 403 for URL: https://ymbdlb.santander.com.br/dl-ticket-services/TicketEndpointService/TicketEndpointService.wsdl
java.io.IOException: Server returned HTTP response code: 403 for URL: https://ymbdlb.santander.com.br/dl-ticket-services/TicketEndpointService/TicketEndpointService.wsdl?wsdl

	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.tryWithMex(RuntimeWSDLParser.java:260)
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:231)
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:194)
	at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:163)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:348)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:306)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:215)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:196)
	at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:192)
	at com.sun.xml.internal.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:104)
	at javax.xml.ws.Service.<init>(Service.java:77)
	at dl.ticket.TicketEndpointService.<init>(TicketEndpointService.java:50)
	at ticketclient.YMBTicketClient.create(YMBTicketClient.java:148)
	at ticketclient.YMBTicketClient.main(YMBTicketClient.java:112)
```

Pode perceber que retornou exatamente o código HTTP 403 que é acesso proibido. Isto está correto, pois usei um certificado auto-assinado.

Se por acaso você está fazendo isso com o certificado correto e está dando HTTP 403, é provável que o Santander ainda não tenha registrado seu certificado com eles. Nesse caso, melhor entrar em contato com o banco.

Até mais!

**Comment by aCidcOde** [comment]
Estou enfrentando o mesmo problema. Porém o banco disse que já registrou o certificado.

**Comment by DenysXavier** [comment]
> Estou enfrentando o mesmo problema. Porém o banco disse que já registrou o certificado.

@aCidcOde, você rodou esse teste também?

Qual o retorno dele?

403 é acesso proibido.

**Comment by aCidcOde** [comment]
@DenysXavier Sim, mas já deu certo, era problema de registro deles mesmo, tentei no outro dia e já funcionou.

**Comment by DenysXavier** [comment]
Oi, @aCidcOde!

Bom saber que funcionou.

Além do mais, aconteceu o mais provável mesmo, o Santander ainda não tinha registrado o certificado.

De todo modo, vou fechar esta issue.

Se você ou @valderind4 virem a necessidade de reabrir, fiquem a vontade.
