### ISSUE TITLE
unable to set private key file: 

### ISSUE THREAD

**Issue by ghost** [DenysXavier/WSBoletoSantander#46]
Segui todos os passos, inclusive que o banco me orientou, e está retornando este erro:

unable to set private key file:
'/caminho/para/o/certificado.pem' type PEM

Não tenho nenhum conhecimento com certificados, não entendi se tem algo a ver com o https por causa do ssl, poderia ter uma explicação melhor no readme sobre os tipos de certificado, de onde comprar, como gerar e converter usando o openssl por exemplo

**Comment by DenysXavier** [comment]
Olá, @lsb31!

Em que momento está dando esse erro?

É quando você vai solicitar o tíquete de registro de boleto?

**Comment by ghost** [comment]
Isso mesmo, na solicitação do tíquete.

```
if (!$response) {
    $error_message = curl_error($ch);
    curl_close($ch);

    throw new \Exception($error_message);
}
```

**Comment by DenysXavier** [comment]
Certo!

Então o problema se dá exatamente no comunicação com o banco usando o curl.

Você configurou corretamente no arquivo _config.ini_ do WSBoletoSantander o caminho e a senha do certificado?

Variáveis `arquivo` e `senha` dentro do grupo `[certificado]`.

**Comment by ghost** [comment]
Sim, meu certificado não tem senha, deixei vazio o campo

**Comment by DenysXavier** [comment]
Olá, @lsb31!

Estive pesquisando seu caso e pelo jeito você está com problema de incompatibilidade entre seu PEM e o WSBoletoSantander.

Pelo que vi, a solução mais rápida será você recriar seu arquivo PEM de forma que inclua toda cadeia de certificados & sua chave-privada.

Eu, por outro lado, tenho que ver uma maneira de implementar uma forma do WSBoletoSantander trabalhar com a chave-privada em um arquivo separado.

Vou supor que você tenha acesso aos arquivos do certificado (que você mandou para o Santander) e da chave (que você gerou na primeira vez). Esses arquivos devem estar na mesma pasta ou diretório, provavelmente, com as extensões .crt e .key.

Primeiro, você vai criar um "storage" de todos os seus objetos criptográficos (certificado e chave-privada)

```console
openssl pkcs12 -export -in <seu_certificado>.crt -inkey <sua_chave>.key -out <nome_do_arquivo_de_saida>.p12
```

Depois, crie um arquivo PEM a partir do arquivo recém criado.

```console
openssl pkcs12 -in <nome_do_arquivo_de_saida>.p12 -nodes -out <nome_do_arquivo_que_será_usado_com_o_wsboletosantander>.pem
```

*Substitua os nomes entre <> com os dados corretos.

Essa solução foi encontrada aqui: https://gist.github.com/stevenhaddox/1501893

Espero que isso ajude!

**Comment by ghost** [comment]
Perfeito, consegui gerar o PEM e comunicar com o banco, agora tem erros que eu vou ter que tratar no meu código.
Mas o problema da issue foi resolvido.
Seria legal colocar estes comandos que vc mandou no readme do projeto.

**Comment by DenysXavier** [comment]
> Perfeito, consegui gerar o PEM e comunicar com o banco, agora tem erros que eu vou ter que tratar no meu código.
> Mas o problema da issue foi resolvido.

Certo!

Problema resolvido. Bom saber!

> Seria legal colocar estes comandos que vc mandou no readme do projeto.

Aliás, o projeto precisa de melhor documentação.

Confesso que isso estou deixando a desejar.

Espero resolver isso o mais breve possível.

Muito obrigado!

**Comment by MrWesleyR** [comment]
> Olá, @lsb31!
> 
> Estive pesquisando seu caso e pelo jeito você está com problema de incompatibilidade entre seu PEM e o WSBoletoSantander.
> 
> Pelo que vi, a solução mais rápida será você recriar seu arquivo PEM de forma que inclua toda cadeia de certificados & sua chave-privada.
> 
> Eu, por outro lado, tenho que ver uma maneira de implementar uma forma do WSBoletoSantander trabalhar com a chave-privada em um arquivo separado.
> 
> Vou supor que você tenha acesso aos arquivos do certificado (que você mandou para o Santander) e da chave (que você gerou na primeira vez). Esses arquivos devem estar na mesma pasta ou diretório, provavelmente, com as extensões .crt e .key.
> 
> Primeiro, você vai criar um "storage" de todos os seus objetos criptográficos (certificado e chave-privada)
> 
> ```
> openssl pkcs12 -export -in <seu_certificado>.crt -inkey <sua_chave>.key -out <nome_do_arquivo_de_saida>.p12
> ```
> 
> Depois, crie um arquivo PEM a partir do arquivo recém criado.
> 
> ```
> openssl pkcs12 -in <nome_do_arquivo_de_saida>.p12 -nodes -out <nome_do_arquivo_que_será_usado_com_o_wsboletosantander>.pem
> ```
> 
> *Substitua os nomes entre <> com os dados corretos.
> 
> Essa solução foi encontrada aqui: https://gist.github.com/stevenhaddox/1501893
> 
> Espero que isso ajude!

Usei este processo para capturar token do Itau usando curl do PHP, caso alguém tenha o mesmo problema, recomendo testar.
