### ISSUE TITLE
Erro: CERTIFICADO INCONSISTENTE

### ISSUE THREAD

**Issue by ghost** [DenysXavier/WSBoletoSantander#47]
Estou conversando com um cara do banco, já mandei o certificado para ele, ele diz que está correto, ele mesmo tentou gerar o PEM e me mandar.

O erro é "Serviço do Santander retornou os seguintes erros: CERTIFICADO INCONSISTENTE"

Este erro lança na função $svc->incluirTitulo($ticket);

Desabilitei o "assegurar_endpoint" para evitar erros de certificado CA, o arquivo PEM e senha estão corretos.

**Comment by lsb31** [comment]
Bom, era

**Comment by ghost** [comment]
O erro era no meu código do convenio, por isso não encontrava o certificado
