### ISSUE TITLE
Access denied: certificate not found-1

### ISSUE THREAD

**Issue by igoralvess** [DenysXavier/WSBoletoSantander#48]
Depois de configurarem o certificado no santander deixei de ter o erro 403 e passei a receber "Access denied: certificate not found-1". Alguém mais teve esse problema?

**Comment by DenysXavier** [comment]
Olá, @igoralvess!

Conseguiu resolver o problema?

Se ainda não, tente usar o caminho absoluto para o arquivo. Por exemplo, ao invés de meusite/certificado.pem, tente algo como /var/www/meusite/certificado.pem (ou C:/meusite/certificado.pem, se for Windows).

**Comment by igoralvess** [comment]
Obrigado pela ajuda @DenysXavier.
Mas o problema era no banco mesmo, eles corrigiram lá e depois eu consegui normalmente.
