### ISSUE TITLE
Caminhos dos arquivos

### ISSUE THREAD

**Issue by luandiego7** [DenysXavier/WSBoletoSantander#49]
Boa tarde!! Tudo bem??
então, estou precisando fazer esse web service.. montei a estrutura e tal.. 
só que eu preciso passar os caminhos dos arquivos/certificados, dinamicamente... o sistema aqui é multi empresa, e cada empresa tem sua pasta... então n posso deixar estático lá. 
Teria como fazer assim? ou só estático mesmo?

**Comment by DenysXavier** [comment]
Olá, @luandiego7!

Infelizmente, só pelo arquivo de configuração mesmo.

Essa biblioteca foi desenvolvida especificamente para onde trabalho e não temos essa necessidade.

Vou marcar esse issue como uma melhoria para tentar encaixá-lo em uma versão futura. Mas, não posso me comprometer com uma data, por enquanto.

**Comment by luandiego7** [comment]
Eita nóis rsrsrs 
Beleza então mano. Vou ver se consigo fazer algumas modificações aqui pra adaptar. 
Muito obrigado! Essa biblioteca ta muitoo show! 
Grande abraço.

**Comment by DenysXavier** [comment]
Eu que agradeço.

**Comment by luandiego7** [comment]
opa, boa tarde amigo. 
Deixa eu aproveitar esse tópico pra tirar mais uma dúvida.. 
vc disse que é necessário pedir pra o Santander cadastrar o certificado lá... 
por onde eu faço isso? Tenho q ligar pro banco? Mando email? Como seria?
Pode me ajudar com isso?
Nos testes aqui, me retornou esse erro: Access denied: certificate not found<.
Desde já, muitoo obrigado!

**Comment by luandiego7** [comment]
opa, boa tarde amigo @DenysXavier 
Deixa eu aproveitar esse tópico pra tirar mais uma dúvida..
vc disse que é necessário pedir pra o Santander cadastrar o certificado lá...
por onde eu faço isso? Tenho q ligar pro banco? Mando email? Como seria?
Pode me ajudar com isso?
Nos testes aqui, me retornou esse erro: Access denied: certificate not found<.
Desde já, muitoo obrigado!
