### ISSUE TITLE
Certificado

### ISSUE THREAD

**Issue by jersobh** [DenysXavier/WSBoletoSantander#5]
Olá pessoal!
Qual é o certificado correto pra usar no Santander? É o e-cnpj A1? Estou tentando comprar na certisign, mas o Santander só diz no email que precisa ser “client authentication” ou “Prova sua identidade para um computador remoto”. Seria um e-CNPJ A1?

**Comment by jersobh** [comment]
É o primeiro da lista aí
https://www.certisign.com.br/certificado-digital/para-empresa/ecnpj/comprar

**Comment by jersobh** [comment]
No email ela disse expressamente que NÃO É SSL.

**Comment by DenysXavier** [comment]
Olá, @jersobh!

Dei uma olhada no site da Certisign e, sinceramente, não sei dizer se o certificado que você está tentando comprar é o ideal.

Muito provavelmente, você terá que comprar um certificado de servidor, pois as trocas de mensagens do webservice é servidor para servidor, então, acredito que seja necessário algo que comprove a identidade de sua máquina, não sua ou de sua empresa especificamente.

Mas, infelizmente, não tenho garantia nenhuma de minhas respostas.

Inclusive, também cheguei a essa conclusão fazendo o questionário da própria Certsign. Neste endereço https://www.certisign.com.br/certificado-digital/escolha-certificado. Comecei escolhendo a penúltima opção "Proteger meu servidor web", depois escolhi a primeira opção em todas as outras perguntas.

Como sugestão, tente entrar em contato com o pessoal da Certsign e pergunte se os parâmetros do certificado digital que você quer comprar atendem os exigidos pelo Santander, creio que eles conseguirão te direcionar para o correto.

Tais parâmetros podem ser encontrados nesse arquivo [doc_ws_boleto_santander.pdf](https://github.com/DenysXavier/WSBoletoSantander/files/877426/doc_ws_boleto_santander.pdf).

**Comment by jersobh** [comment]
Validamos com o Santander, o certificado é esse mesmo (e-CNPJ A1). É um .pfx e à partir dele gerei o .cer (.crt) e .pem.

**Comment by DenysXavier** [comment]
Boa tarde, @jersobh!

Perfeito.

Boa sorte com a integração!

**Comment by brtzz** [comment]
No meu caso estou usando para um e-commerce, e o Santander validou um certificado comum de domínio

**Comment by DenysXavier** [comment]
Issue parada há muito tempo sem comentários.

Aparentemente, problema foi solucionado.
