### ISSUE TITLE
Dúvidas sobre percentuais

### ISSUE THREAD

**Issue by coffeverton** [DenysXavier/WSBoletoSantander#51]
Olá, estou tentando trabalhar com o webservice do Santander, mas a empresa que está me prestando suporte é muito ruim, então vou perguntar aqui.

Para os parâmetros de Multa e Juros eu preciso passar o percentual ou o valor calculado?
Por exemplo:
Valor Boleto: R$50,00
Multa: 2%
Juros/dia: 0,33% por dia

Neste caso, eu preciso passar R$1,00 e R$0,16 (calculados) ou 2% e 0,33%?

Obs: Não estou usando a biblioteca, estou consumindo diretamente usando Soap.

Agradeço qualquer ajuda!

**Comment by DenysXavier** [comment]
Porcentagem mesmo. O Santander se vira para calcular.
Seu conceito de juros também está certo. É por dia (PRO RATA).

**Comment by coffeverton** [comment]
Obrigado!
Só preciso fazer uma correção no meu cálculo:
Aqui na empresa, cobramos uma multa de 2% por atraso, e mais juros de mora de 1% ao mês.
No caso do boleto de R$50,00, ficaria assim:
Multa: R$ 1,00 (2%)
Juros por dia: R$0,01 (1% ao mês, dividido por 30 dias)

Esse cálculo pode parecer um pouco óbvio, mas é difícil de alguém dar essa informação.
