### ISSUE TITLE
Documentação do WebService

### ISSUE THREAD

**Issue by guicouto** [DenysXavier/WSBoletoSantander#52]
Boa tarde @DenysXavier ,
Primeiramente gostaria de parabenizar por essa contribuição, tenho certeza que ajuda e ajudará muitas pessoas.

O que eu gostaria de ver com você, é se você possui a documentação do WebService do Santander, pode ser um PDF ou DOC. 

Antes de implementar, gostaria de dar uma lida para entender melhor como funciona tudo.

Desde já agradeço pela atenção e parabéns mais uma vez.

**Comment by DenysXavier** [comment]
Olá, @guicouto!

Só para eu entender melhor, você quer a documentação desse projeto ou do XML do SOAP do banco Santander?

**Comment by guicouto** [comment]
O do próprio Santander mesmo (XML SOAP). Para entender a fundo o seu projeto está fazendo e conseguir implantá-la da melhor forma possível.

**Comment by DenysXavier** [comment]
@guicouto, segue o arquivo do Santander.

Esse é a última versão que tenho. Geralmente é o próprio pessoal que utiliza o projeto que acaba me conseguindo.

[Layout.XML.Cobranca.OnLine.Setembro.v1.9.pdf](https://github.com/DenysXavier/WSBoletoSantander/files/3956958/Layout.XML.Cobranca.OnLine.Setembro.v1.9.pdf)

**Comment by guicouto** [comment]
Muito obrigado @DenysXavier
