### ISSUE TITLE
TIPO DE DOCUMENTO INVALIDO

### ISSUE THREAD

**Issue by luandiego7** [DenysXavier/WSBoletoSantander#56]
Bom dia pessoal! Tudo bem??
Mais uma vez pedindo socorro rsrs 
Agora o problema é o seguinte, consegui fazer a comunicação com o banco.. 
E agora ele tá me retornando o seguinte erro:
"TIPO DE DOCUMENTO INVALIDO"
Alguém sabe qual parâmetro para corrigir isso? O por que deste erro? 

Desde já grato!! 
Abraços

**Comment by DenysXavier** [comment]
Olá, @luandiego7 !

Incrivelmente ainda não peguei esse erro.

Mas aparenta ser algo com a validação do documento do lado do serviço do Santander.

Verifique o que você está mandando no parâmetro `$tipoDoc` da instância de Pagador.

Se for "01", então, o valor de `$numeroDoc` deve ser um CPF válido. Caso seja "02", então, espera-se um CNPJ válido.

Em ambos os casos, o valor informado DEVE ser composto apenas de números, nada de ponto (.), traço (-) ou barra (/).

Espero que isso ajude.

**Comment by luandiego7** [comment]
@DenysXavier era exatamente isso. 
O tipo do cliente acabou não indo. Já ajustei e funcionou. 
Muito obrigadoo amigo!! 
Grande abraço!!
