### ISSUE TITLE
Calcular dígito do nosso número

### ISSUE THREAD

**Issue by DenysXavier** [DenysXavier/WSBoletoSantander#6]
No WS, a tag do Nosso Número tem a capacidade de 13 caracteres. Entretanto, o Nosso Número é composto por apenas 12 dígitos. A 13a posição é o dígito verificador. Então, é necessário calcular qual é esse dígito e possibilitar obter o nosso número com e sem dígito.

**Comment by jersobh** [comment]
function modulo_11($num, $base=9, $r=0)  {
                                    
    $soma = 0;
    $fator = 2;
    
    for ($i = strlen($num); $i > 0; $i--) {
        $numeros[$i] = substr($num,$i-1,1);
        $parcial[$i] = $numeros[$i] * $fator;
        $soma += $parcial[$i];
        if ($fator == $base) {
            $fator = 1;
        }
        $fator++;
    }
    
    if ($r == 0) {
        $soma *= 10;
        $digito = $soma % 11;
        if ($digito == 10) {
            $digito = 0;
        }
        return $digito;
    } elseif ($r == 1){
        $resto = $soma % 11;
        return $resto;
    }
}

function digitoVerificador_nossonumero($numero) {
	$resto2 = modulo_11($numero, 9, 1);
     $digito = 11 - $resto2;
     if ($digito == 10 || $digito == 11) {
        $dv = 0;
     } else {
        $dv = $digito;
     }
	 return $dv;
}
